// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var squareVerifier = artifacts.require('verifier')

// Test verification with correct proof
let proof = require('../../zokrates/code/square/proof')

// - use the contents from proof.json generated from zokrates steps
contract('TestSquareVerifier', accounts => {

    const account_one = accounts[0];

    // - use the contents from proof.json generated from zokrates steps
}
    
// Test verification with incorrect proof
